### ISSUE TITLE
Weird manifestation for spectators

### ISSUE THREAD

**Issue by Annihilator** [ravimohan1991/SmartCTF#1]
Sometimes the following representation is shown to game spectators:

Roughly speaking, this seems to happen when there's activity regardging the flag (taken, dropped...), but I can't be 100% sure.
![Untitled](https://user-images.githubusercontent.com/760349/84509886-a7fa7d00-acc4-11ea-80f6-938d419bb08a.jpg)

**Comment by Annihilator** [comment]
Hmm... Didn't have CountryFlags2 in ServerPackages... could that be the reason?

**Comment by ravimohan1991** [comment]
I couldn't reproduce this bug in offline gameplay with SmartCTF. Does this bug appear with only SmartCTF on? Could it be related to some other mutator?

**Comment by Annihilator** [comment]
Try online on our server, you will catch it quickly I hope: ut2004://104.40.129.201:7777.
It happens only when SmartCTF is active, but I guess it could be related to the interaction with another mutator (UTComp or some other we're running). In any case I can confirm this doesn't happen when SmartCTF is not used.

**Comment by Annihilator** [comment]
It seems that you're right, some weird conflict with a different mutator... closing this, sorry.
