### ISSUE TITLE
No Overtime not working properly

### ISSUE THREAD

**Issue by Annihilator** [ravimohan1991/SmartCTF#2]
The No Overtime function doesn't appear to work properly. The game ends, but is left in a stuck state; the game timer keeps ticking but no players can join.
Feel free to examine my own No Overtime mutator for inspiration, which handles this properly (unlike some other details).

**Comment by ravimohan1991** [comment]
So I looked at your code and it seems to handle the draw more rigorously.  
`function NOEndGame(PlayerController Admin, bool bForce)
{
	local Controller C;
	local name EndSound;
	local Sound EndSoundSound;
	local string sNick;

	EndSound = 'That_was_a_close_match';
	EndSoundSound = sound'AnnouncerMain.That_was_a_close_match';
	TeamGame(Level.Game).EndGameSoundName[0] = EndSound;
	TeamGame(Level.Game).EndGameSoundName[1] = EndSound;
	TeamGame(Level.Game).AltEndGameSoundName[0] = EndSound;
	TeamGame(Level.Game).AltEndGameSoundName[1] = EndSound;
	DeathMatch(Level.Game).RemainingTime = 0;
	Level.Game.GameReplicationInfo.RemainingTime = 0;
	Level.Game.GameReplicationInfo.RemainingMinute = 0;
	Level.Game.bGameEnded = True;
	Level.Game.TriggerEvent('EndGame',self,None);
	Level.Game.EndLogging("Draw");
	Level.Game.Broadcast(Instigator.Controller, "MATCH DRAW", 'CriticalEvent');
	PlayerController(Instigator.Controller).ClientPlaySound(EndSoundSound);
	BroadcastLocalizedMessage(class'NoOvertimeDrawMessage');
	return;
}`
especially `Level.Game.bGameEnded = True;`. This was not included in Epic's default handling of endgame. Their code looks like
`for ( P=Level.ControllerList; P!=None; P=P.nextController )
	{
		P.GameHasEnded();
		Player = PlayerController(P);
		if ( Player != None )
		{
			Player.ClientSetBehindView(true);
			Player.ClientSetViewTarget(EndGameFocus);
			Player.SetViewTarget(EndGameFocus);
			if ( !Player.PlayerReplicationInfo.bOnlySpectator )
				PlayWinMessage(Player, (Player.PlayerReplicationInfo.Team == GameReplicationInfo.Winner));
			Player.ClientGameEnded();
			if ( CurrentGameProfile != None )
				CurrentGameProfile.bWonMatch = (Player.PlayerReplicationInfo.Team == GameReplicationInfo.Winner);
		}
	}`
Anyways, I certainly can edit my code with your suggestions.

**Comment by ravimohan1991** [comment]
So I looked at your code and it seems to handle the draw more rigorously.  
 ```
function NOEndGame(PlayerController Admin, bool bForce)
{
	local Controller C;
	local name EndSound;
	local Sound EndSoundSound;
	local string sNick;

	EndSound = 'That_was_a_close_match';
	EndSoundSound = sound'AnnouncerMain.That_was_a_close_match';
	TeamGame(Level.Game).EndGameSoundName[0] = EndSound;
	TeamGame(Level.Game).EndGameSoundName[1] = EndSound;
	TeamGame(Level.Game).AltEndGameSoundName[0] = EndSound;
	TeamGame(Level.Game).AltEndGameSoundName[1] = EndSound;
	DeathMatch(Level.Game).RemainingTime = 0;
	Level.Game.GameReplicationInfo.RemainingTime = 0;
	Level.Game.GameReplicationInfo.RemainingMinute = 0;
	Level.Game.bGameEnded = True;
       C = Level.ControllerList;
	loop:
	if (C != None)
	{
		if (!C.IsA('ScriptedTriggerController'))
		{
			sNick = C.PlayerReplicationInfo.PlayerName;
			if ((MessagingSpectator(C) == None) && (sNick != "WebAdmin") && (sNick != "BullShit") && (sNick != "DemoRecSpectator"))
				if (C.IsA('PlayerController') || C.PlayerReplicationInfo.bBot)
				{
					C.ClientGameEnded();
					C.GameHasEnded();
				}
		}
		C = C.nextController;
		goto loop;
	}
	Level.Game.TriggerEvent('EndGame',self,None);
	Level.Game.EndLogging("Draw");
	Level.Game.Broadcast(Instigator.Controller, "MATCH DRAW", 'CriticalEvent');
	PlayerController(Instigator.Controller).ClientPlaySound(EndSoundSound);
	BroadcastLocalizedMessage(class'NoOvertimeDrawMessage');
	return;
} 
```
especially  `Level.Game.bGameEnded = True;`   This was not included in Epic's default handling of endgame. Their code looks like
```
 for ( P=Level.ControllerList; P!=None; P=P.nextController )
	{
		P.GameHasEnded();
		Player = PlayerController(P);
		if ( Player != None )
		{
			Player.ClientSetBehindView(true);
			Player.ClientSetViewTarget(EndGameFocus);
			Player.SetViewTarget(EndGameFocus);
			if ( !Player.PlayerReplicationInfo.bOnlySpectator )
				PlayWinMessage(Player, (Player.PlayerReplicationInfo.Team == GameReplicationInfo.Winner));
			Player.ClientGameEnded();
			if ( CurrentGameProfile != None )
				CurrentGameProfile.bWonMatch = (Player.PlayerReplicationInfo.Team == GameReplicationInfo.Winner);
		}
	} 
```
Anyways, I certainly can edit my code with your suggestions.

**Comment by Annihilator** [comment]
Please, feel free to do so. It's not my code though, the original code is from a different mutator (UT2Vote).

**Comment by ravimohan1991** [comment]
I have implemented your code in SmartCTF. I am attaching the test version. Let me know if it is upto your satisfaction
[System.zip](https://github.com/ravimohan1991/SmartCTF/files/4801028/System.zip)

**Comment by Annihilator** [comment]
Works wonderfully, thank you. Even the announcer sounds, which I couldn't get to work (not that I tried too much, tbh). Also, feel free to toss out the debugging MATCH DRAW message to console at your convenience; it was only a stopgap until I get the on-screen message to show up.
